// Generated by gencpp from file drone_msgs/ExecStatus.msg
// DO NOT EDIT!


#ifndef DRONE_MSGS_MESSAGE_EXECSTATUS_H
#define DRONE_MSGS_MESSAGE_EXECSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace drone_msgs
{
template <class ContainerAllocator>
struct ExecStatus_
{
  typedef ExecStatus_<ContainerAllocator> Type;

  ExecStatus_()
    : header()
    , exec_flag(0)  {
    }
  ExecStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , exec_flag(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _exec_flag_type;
  _exec_flag_type exec_flag;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(EXEC_STATUS_INIT)
  #undef EXEC_STATUS_INIT
#endif
#if defined(_WIN32) && defined(EXECY_STATUS_WAIT_TARGET)
  #undef EXECY_STATUS_WAIT_TARGET
#endif
#if defined(_WIN32) && defined(EXEC_STATUS_GEN_NEW_TRAJ)
  #undef EXEC_STATUS_GEN_NEW_TRAJ
#endif
#if defined(_WIN32) && defined(EXEC_STATUS_REPLAN_TRAJ)
  #undef EXEC_STATUS_REPLAN_TRAJ
#endif
#if defined(_WIN32) && defined(EXEC_STATUS_EXEC_TRAJ)
  #undef EXEC_STATUS_EXEC_TRAJ
#endif
#if defined(_WIN32) && defined(EXEC_STATUS_EMERGENCY_STOP)
  #undef EXEC_STATUS_EMERGENCY_STOP
#endif

  enum {
    EXEC_STATUS_INIT = 0u,
    EXECY_STATUS_WAIT_TARGET = 1u,
    EXEC_STATUS_GEN_NEW_TRAJ = 2u,
    EXEC_STATUS_REPLAN_TRAJ = 3u,
    EXEC_STATUS_EXEC_TRAJ = 4u,
    EXEC_STATUS_EMERGENCY_STOP = 5u,
  };


  typedef boost::shared_ptr< ::drone_msgs::ExecStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone_msgs::ExecStatus_<ContainerAllocator> const> ConstPtr;

}; // struct ExecStatus_

typedef ::drone_msgs::ExecStatus_<std::allocator<void> > ExecStatus;

typedef boost::shared_ptr< ::drone_msgs::ExecStatus > ExecStatusPtr;
typedef boost::shared_ptr< ::drone_msgs::ExecStatus const> ExecStatusConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone_msgs::ExecStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone_msgs::ExecStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drone_msgs::ExecStatus_<ContainerAllocator1> & lhs, const ::drone_msgs::ExecStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.exec_flag == rhs.exec_flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drone_msgs::ExecStatus_<ContainerAllocator1> & lhs, const ::drone_msgs::ExecStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drone_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::drone_msgs::ExecStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_msgs::ExecStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_msgs::ExecStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_msgs::ExecStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_msgs::ExecStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_msgs::ExecStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone_msgs::ExecStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cedea8b1481a61431e7301e6e90fa742";
  }

  static const char* value(const ::drone_msgs::ExecStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcedea8b1481a6143ULL;
  static const uint64_t static_value2 = 0x1e7301e6e90fa742ULL;
};

template<class ContainerAllocator>
struct DataType< ::drone_msgs::ExecStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone_msgs/ExecStatus";
  }

  static const char* value(const ::drone_msgs::ExecStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone_msgs::ExecStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"uint8 exec_flag\n"
"\n"
"uint8 EXEC_STATUS_INIT = 0\n"
"uint8 EXECY_STATUS_WAIT_TARGET = 1\n"
"uint8 EXEC_STATUS_GEN_NEW_TRAJ = 2\n"
"uint8 EXEC_STATUS_REPLAN_TRAJ = 3\n"
"uint8 EXEC_STATUS_EXEC_TRAJ = 4\n"
"uint8 EXEC_STATUS_EMERGENCY_STOP = 5\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::drone_msgs::ExecStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone_msgs::ExecStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.exec_flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone_msgs::ExecStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone_msgs::ExecStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "exec_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.exec_flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_MSGS_MESSAGE_EXECSTATUS_H
